### ISSUE TITLE
Relative paths used within the package itself

### ISSUE THREAD

**Issue by louisegrimble** [haniffalab/solosis#28] opened 2024-10-31 16:31 UTC
Relative paths used within the package itself, need to find best way to call on relative paths from outside of solosis directory.

example of current error:
```
$ /nfs/users/nfs_l/lg28/repos/solosis/solosis-cli cellranger --sample=HCA_SkO13919077
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/scratch126/cellgen/team298/lg28/irods_test/bin/alignment/cellranger/submit.sh'
```

**Comment by davehorsfall** [comment] 2024-11-13 17:25
Duplicate of #24

**Closed by davehorsfall** 2024-11-13 17:25 UTC
Labels: bug
